version: '3'

services:

  devcontainers:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    env_file:
      - .env

  redis:
    image: redis:latest
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    env_file:
      - .env